### ISSUE TITLE
Allow user to set logging level in TOML collection

### ISSUE THREAD

**Issue by puffyCid** [puffyCid/artemis#3]
**What new feature do you think would be cool to add to artemis?**
Currently the log level for artemis is `WARNING` and there is no way to change this. However, it should be easy make that configurable in the TOML collection.  Ex:
```toml
system = "macos"

[output]
name = "macos_collection"
directory = "./tmp"
format = "jsonl"
compress = true
endpoint_id = "6c51b123-1522-4572-9f2a-0bd5abd81b82"
collection_id = 1
output = "local"
logging = "error"
```

**Describe the solution you'd like**
Allow the user to set logging level
